/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single participant's key share */
export interface NapiKeygenOutput {
  key_package: Array<number>
  public_key_package: Array<number>
  identifier: Array<number>
}
/** Output from centralized key generation */
export interface NapiCentralizedKeygenOutput {
  private_key: Array<number>
  keygen_outputs: Array<NapiKeygenOutput>
  public_key: Array<number>
}
/** Generate a 2-of-2 threshold Ed25519 key using centralized key generation. */
export declare function napiKeygenCentralizedEd25519(): NapiCentralizedKeygenOutput
/** Import an existing Ed25519 secret key and split it into threshold shares. */
export declare function napiKeygenImportEd25519(secretKey: Array<number>): NapiCentralizedKeygenOutput
/** Extract signing_share and verifying_share from a serialized key_package. */
export interface NapiKeyPackageShares {
  signing_share: Array<number>
  verifying_share: Array<number>
}
/** Extract signing_share and verifying_share from a serialized Ed25519 key_package. */
export declare function napiExtractKeyPackageSharesEd25519(keyPackageBytes: Array<number>): NapiKeyPackageShares
/** Reconstruct a key_package from signing_share, verifying_share, identifier, and verifying_key. */
export declare function napiReconstructKeyPackageEd25519(signingShare: Array<number>, verifyingShare: Array<number>, identifier: Array<number>, verifyingKey: Array<number>, minSigners: number): Array<number>
/** Reconstruct a public_key_package from verifying_shares, identifiers, and verifying_key. */
export declare function napiReconstructPublicKeyPackageEd25519(clientVerifyingShare: Array<number>, clientIdentifier: Array<number>, serverVerifyingShare: Array<number>, serverIdentifier: Array<number>, verifyingKey: Array<number>): Array<number>
/** Output from a signing round 1 (commitment) */
export interface NapiSigningCommitmentOutput {
  nonces: Array<number>
  commitments: Array<number>
  identifier: Array<number>
}
/** Output from a signing round 2 (signature share) */
export interface NapiSignatureShareOutput {
  signature_share: Array<number>
  identifier: Array<number>
}
/** Final aggregated signature */
export interface NapiSignatureOutput {
  signature: Array<number>
}
/** Round 1: Generate signing commitments for a participant. */
export declare function napiSignRound1Ed25519(keyPackage: Array<number>): NapiSigningCommitmentOutput
/** Round 2: Generate a signature share for a participant. */
export declare function napiSignRound2Ed25519(message: Array<number>, keyPackage: Array<number>, nonces: Array<number>, allCommitments: any): NapiSignatureShareOutput
/** Aggregate signature shares into a final threshold signature. */
export declare function napiAggregateEd25519(message: Array<number>, allCommitments: any, allSignatureShares: any, publicKeyPackage: Array<number>): NapiSignatureOutput
/** Verify a signature against a public key. */
export declare function napiVerifyEd25519(message: Array<number>, signature: Array<number>, publicKeyPackage: Array<number>): boolean
/** Output from SSS split operation */
export interface NapiSssSplitOutput {
  key_packages: Array<NapiKeygenOutput>
}
/** Output from SSS extend operation */
export interface NapiSssExtendOutput {
  new_key_packages: Array<NapiKeygenOutput>
  public_key_package: Array<number>
}
/**
 * Split an Ed25519 signing share into SSS shares for distribution to KSN nodes.
 *
 * # Arguments
 * * `signing_share` - The 32-byte signing share to split
 * * `identifiers` - Array of 32-byte identifiers for each share (one per node)
 * * `min_signers` - Minimum number of shares required to reconstruct (threshold)
 *
 * # Returns
 * Key packages for each identifier
 */
export declare function napiSssSplitEd25519(signingShare: Array<number>, identifiers: Array<Array<number>>, minSigners: number): NapiSssSplitOutput
/**
 * Combine SSS shares to recover the original signing share.
 *
 * # Arguments
 * * `key_packages` - Array of serialized key packages (at least min_signers required)
 *
 * # Returns
 * The recovered 32-byte signing share
 */
export declare function napiSssCombineEd25519(keyPackages: Array<Array<number>>): Array<number>
/**
 * Extend existing shares to add new participants without changing the polynomial.
 *
 * This is used when a KSN node loses data and needs a new share computed from
 * the remaining active nodes' shares.
 *
 * # Arguments
 * * `key_packages` - Existing key packages from active nodes (at least min_signers required)
 * * `new_identifiers` - 32-byte identifiers for the new participants
 * * `public_key_package` - The existing public key package
 *
 * # Returns
 * New key packages for the additional identifiers
 */
export declare function napiSssExtendEd25519(keyPackages: Array<Array<number>>, newIdentifiers: Array<Array<number>>, publicKeyPackage: Array<number>): NapiSssExtendOutput
