name: Deploy Oko Apps
env:
  VERCEL_ORG_ID: ${{ envs.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID__OKO_DEMO_WEB: ${{ envs.VERCEL_PROJECT_ID__OKO_DEMO_WEB }}
  VERCEL_PROJECT_ID__CT_DASHBOARD: ${{ envs.VERCEL_PROJECT_ID__CT_DASHBOARD }}
  VERCEL_PROJECT_ID__USER_DASHBOARD: ${{ envs.VERCEL_PROJECT_ID__USER_DASHBOARD }}
  VERCEL_PROJECT_ID__OKO_ATTACHED: ${{ envs.VERCEL_PROJECT_ID__OKO_ATTACHED }}
on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: "Git tag for deployment (format: develop/v0.0.1 or release/v0.0.1)"
        required: true
        type: string
      oko_app:
        description: 'App'
        required: true
        type: choice
        options:
          - 'demo_web'
          - 'oko_attached'
          - 'user_dashboard'
          - 'ct_dashboard'

jobs:
  publish:
    runs-on: ubuntu-22.04
    container:
      image: node:22.0.0-alpine
    timeout-minutes: 60
    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Check git tag
        run: node ./internals/github/dist/validate_git_tag.js
        env:
          GIT_TAG: "${{ inputs.git_tag }}"

      - name: Set Vercel Project Id 4
        run: |
          PROJ_ID=$(node ./internals/github/dist/get_vercel_proj_id.js)
          echo $PROJ_ID
      #     echo "VERCEL_PROJECT_ID=$PROJ_ID" >> "$GITHUB_OUTPUT"
        env:
          OKO_APP: "${{ inputs.oko_app }}"
      #
      # - name: Enable Corepack
      #   run: corepack enable
      #
      # - name: Yarn version
      #   run: yarn -v
      #
      # - name: Install Vercel CLI
      #   run: npm install -g vercel@latest
      #
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      #
      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      #
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
